# default values
all:
  yahoo:
    app_id: reviewsby.us
    geocode: http://api.local.yahoo.com/MapsService/V1/geocode
  search:
    body_weight:         1
    title_weight:        2
    tag_weight:          3
    results_max:         10
    default_radius:      50
    city_radius:         25
