cli:
  controller:
    class: sfConsoleController
  request:
    class: sfConsoleRequest

test:
  storage:
    class: sfSessionTestStorage

all:
  user:
    class: sfGuardSecurityUser
#  controller:
#    class: sfFrontWebController
#
#  request:
#    class: sfWebRequest
#
#  user:
#    class: myUser
#
#  storage:
#    class: sfSessionStorage
#    param:
#      session_name: symfony
#
#  execution_filter:
#    class: sfExecutionFilter
#
#  security_filter:
#    class: sfBasicSecurityFilter
#
#  view_cache:
#    class: sfFileCache
