<?php
// auto-generated by sfPropelCrud
// date: 02/18/2006 16:27:56
?>
<h1>user</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Userid</th>
  <th>Email</th>
  <th>Password md5</th>
  <th>Open</th>
</tr>
</thead>
<tbody>
<?php foreach ($users as $user): ?>
<tr>
    <td><?php echo link_to($user->getId(), 'user/show?id='.$user->getId()) ?></td>
      <td><?php echo $user->getUserid() ?></td>
      <td><?php echo $user->getEmail() ?></td>
      <td><?php echo $user->getPasswordMd5() ?></td>
      <td><?php echo $user->getOpenId() ?></td>
  </tr>
<?php endforeach ?>
</tbody>
</table>

<?php echo link_to ('create', 'user/edit') ?>
