generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Location
    theme:            default
    list:
      fields:
        country_id:   { filter_is_empty: true }
      max_per_page: 10
      display:        [=id, restaurant, name, address, city, state, zip, country_id]
      filters: [restaurant_id, country_id]
      actions:
        _create: -
        batch: { name: Batch Update, action: batch }
    edit:
      display: [Restaurant, name, address, city, state, zip, country_id, latitude, longitude, phone]