menuitems_in_restaurant:
  url: /menuitem/inRestaurant/:restaurant/:scope/:page
  param: { module: menuitem, action: inRestaurant }
restaurant_list:
  url: /restaurants/*
  param: { module: location, action: index }
indexhack:
  url: /index
  param: { module: default, action: index }

menu_item_image:
  url: /menuitem_image/:hash
  param: { module: menuitem_image, action: show }
menu_item_image_add:
  url: /restaurant/:restaurant/menu/:stripped_title/add/image
  param: { module: menuitem_image, action: add }
  
menu_item_edit:
  url: /restaurant/:restaurant/menu/:stripped_title/edit
  param: { module: menuitem, action: edit }  
profile:
  url: /profile/:user
  param: { module: user, action: profile}
about:
  url: /about
  param: { module: default, action: static, page: about}
feed_latest_georss:
  url: /feed/latest.georss
  param: { module: feed, action: latestRestaurantLocations}
latest_restaurants_page:
  url: /latest/:page
  param: { module: restaurant, action: latest }

latest_restaurants:
  url: /latest
  param: { module: restaurant, action: latest }
register:
  url: /register
  param: { module: user, action: register }
search_restaurant:
  url:   /search/*
  param: { module: restaurant, action: search }

feedback:
  url:  /feedback
  param: { module: feedback, action: index }

feedback_location:
  url: /feedback/location/:restaurant/:location
  param: { module: feedback, action: location }
popular_tags:
  url:   /popular_tags
  param: { module: tag, action: popular }
tag: 
  url:   /tag/:tag 
  param: { module: tag, action: show }
feed_tag_georss:
  url: /tag/:tag/geo.rss
  param: { module: feed, action: tagGeoRss}
  
tag_remove:
  url: /tag_remove/:menuitem_hash/:tag
  param: { module: tag, action: remove }
restaurant_tag_remove:
  url: /restaurant_tag_remove/:restaurant/:tag
  param: { module: tag, action: removeRestaurant }
restaurant_tag_add:
  url: /restaurant_tag_add
  param: { module: tag, action: addRestaurant }  
tag_add: 
  url:   /tag_add 
  param: { module: tag, action: add }
tag_autocomplete: 
  url:   /tag_autocomplete 
  param: { module: tag, action: autocomplete } 

feed_action:
  url: /feed/:action
  param: { module: feed }

restaurant_add:
  url: /add/restaurant
  param: { module: restaurant, action: edit }
restaurant_add_comment:
  url: /restaurant/:stripped_title/review
  param: { module: restaurant, action: addComment }
# default rules
user:
  url:   /user/:action/*
  param: { module: user }
restaurant_update:
  url: /restaurant/update
  param: { module: restaurant, action: update}
restaurant_edit_description:
  url: /restaurant/:stripped_title/edit
  param: { module: restaurant, action: editInformation }
menu_item:
  url: /restaurant/:restaurant/menu/:stripped_title
  param: { module: menuitem, action: show }
menu_item_add:
  url: /restaurant/:restaurant/add/item
  param: { module: menuitem, action: edit }
menuitem_add_comment:
  url: /restaurant/:restaurant/menu/:stripped_title/comment
  param: { module: menuitem, action: addComment }
restaurant:
  url: /restaurant/:stripped_title
  param: { module: restaurant, action: show }

menu_item_feed:
  url: /restaurant/:stripped_title/feed  
  param: { module: feed, action: menuItems }
location:
  url: /restaurant/:restaurant/location/:location
  param: { module: location, action: show }
  
location_add:
  url: /restaurant/:restaurant/add/location
  param: { module: location, action: edit }

restaurant_reindex:
  url: /reindex
  param: { module: restaurant, action: reindex}
restaurant_index:
  url: /restaurant
  param: { module: restaurant, action: index}

openid_signin:
  url:  /openid
  param: { module: openid, action: signin }

openid_finishauth:
  url: /openid/finish
  param: { module: openid, action: finishAuth}

# sfGuard

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

# Defaults 

homepage:
  url:   /
  param: { module: default, action: index }

default:
  url:   /:module/:action/*