prod:
  .settings:
    no_script_name:           on

dev:
  .settings:
    # E_ALL | E_STRICT = 4095
    error_reporting:        4095
    web_debug:              on
    cache:                  off
    stats:                  off
    no_script_name:         off
    etag:                   off

test:
  .settings:
    # E_ALL | E_STRICT & ~E_NOTICE = 2047
    error_reporting:        2047
    cache:                  off
    stats:                  off
    web_debug:              off
    no_script_name:         off
    etag:                   off

all:

  .actions:
    login_module:           sfGuardAuth
    login_action:           signin

    secure_module:          sfGuardAuth
    secure_action:          signin

#    default_module:         default
#    default_action:         index
#
#    error_404_module:       default
#    error_404_action:       error404
#
#
#    module_disabled_module: default
#    module_disabled_action: disabled
#
#
#    unavailable_module:     default
#    unavailable_action:     unavailable
#
  .settings:
    activated_modules:      [default, sfGuardAuth]
#    available:              on
#
#    module_accessor:        module
#    action_accessor:        action
#
#    path_info_array:        SERVER
#    path_info_key:          PATH_INFO
#
#    url_format:             PATH
#
#    use_database:           on
#
#    use_security:           on
#
#    compressed:             on
#
#    tidy:                   on
#
#    i18n:                   off
#
    timeout:                86400
#
#    suffix:                 .
#
#    standard_helpers:       [Partial, Cache, Form]
#
#    max_forwards:           5
#
#    web_debug:              off
#
#    cache:                  on
#    default_cache_lifetime: 86400
#
#    no_script_name:         on
#
#    stats:                  off
#
#    # E_COMPILE_ERROR | E_ERROR | E_CORE_ERROR | E_USER_ERROR = 337
#    error_reporting:        337
#
#    rich_text_js_dir:       js/tiny_mce
#
#    safe_slot:              on
#
#    use_flash:              on
#
#
#    strip_comments:         off
#
#    etag:                   on
