default:
  http_metas:
    content-type: text/html; charset=utf-8

  metas:
    title:        reviewsby.us
    robots:       index, follow
    description:  A collection of dish and restaurant reviews.
    keywords:     menus food menu tags restaurants web2.0 eats drinks openid
    language:     en

  stylesheets:    [home, main, extra]

  javascripts:    [%SF_PROTOTYPE_WEB_DIR%/js/prototype, %SF_PROTOTYPE_WEB_DIR%/js/effects]

  has_layout:     on
  layout:         layout

  slots:          {}

  use_default_slots: on