default:
  http_metas:
    content-type: text/html; charset=utf-8

  metas:
    title:        track your favorite meals from your favorite restaurants // meal advisor
    robots:       index, follow
    description:  Choose your meal wisely...
    keywords:     menus food menu tags restaurants web2.0 eats drinks openid reviewsby.us meal advisor
    language:     en

  stylesheets:    [http://yui.yahooapis.com/2.4.1/build/reset-fonts-grids/reset-fonts-grids.css, main]

  javascripts:    [%SF_PROTOTYPE_WEB_DIR%/js/prototype, %SF_PROTOTYPE_WEB_DIR%/js/effects]

  has_layout:     on
  layout:         layout

  slots:          {}

  use_default_slots: on