rendering: ~
web_debug: 
  enabled: false

facebook:
  class: sfFacebookFilter

myFacebook:
  class: myFacebookFilter

security:  ~

# generally, you will want to insert your own filters here

cache:     ~
common:    ~
flash:     ~
execution: ~
