# default rules
link_accounts:
  url:  /link_accounts
  param: { module: profile, action: linkAccounts }

homepage:
  url:   /
  param: { module: homepage, action: index }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
