dev:
  propel:
    class:          sfPropelDatabase
    param:
      dsn:          mysql://root:@localhost/rbu
all:
  propel:
    class:          sfPropelDatabase
    param:
      dsn:          mysql://mym:mznipul8@mysql.mymen.us/mymenus
