dev:
  propel:
    class:          sfPropelDatabase
    param:
      dsn:          mysql://root:@localhost/rbu
all:
  propel:
    class:          sfPropelDatabase
    param:
      dsn:          mysql://rbu:yicdogh$@localhost/rbu