propel: 
  profile: 
    _attributes: {phpName: Profile}
    id: 
    userid: { type: integer, index: unique }
    email: varchar(128)
    openid: varchar(255)
    preferences: longvarchar
    updated_at: 
    created_at: 
  restaurant: 
    _attributes: { phpName: Restaurant }
    id: 
    name: 
      type: varchar
      size: 255
    stripped_title: 
      type: varchar
      size: 128
    approved: 
      type: boolean
    average_rating: 
      type: float
      size: 2
      scale: 1
    num_ratings: 
      type: integer
    version_id: 
      type: integer
      foreignTable: restaurant_version
      foreignReference: id
    updated_at: 
    created_at: 
  restaurant_search_index: 
    _attributes: 
      phpName: RestaurantSearchIndex
    restaurant_id: 
    word: 
      type: varchar
      size: 255
      index: true
    weight: 
      type: integer
  restaurant_version: 
    _attributes: 
      phpName: RestaurantVersion
    id: 
      type: integer
      required: true
      primaryKey: true
      autoincrement: true
    chain: 
      type: boolean
    description: 
      type: longvarchar
    html_description: 
      type: longvarchar
    url: 
      type: varchar
      size: 255
    created_at: 
      type: TIMESTAMP
    restaurant_id: 
    user_id: 
      type: integer
      onDelete: setnull
      foreignTable: profile
      foreignReference: id
  location: 
    _attributes: 
      phpName: Location
    id: 
      type: integer
      primaryKey: true
      autoIncrement: true
    restaurant_id:
    stripped_title: 
      type: varchar
      size: 255
    name: 
      type: varchar
      size: 255
    address: 
      type: varchar
      size: 255
    city: 
      type: varchar
      size: 128
    state: 
      type: varchar
      size: 16
    zip: 
      type: varchar
      size: 9
    country_id: 
      type: char
      size: 2
      foreignTable: country
      foreignReference: iso
    latitude: 
      type: float
      size: 10
      scale: 7
    longitude: 
      type: float
      size: 10
      scale: 7
    phone: 
      type: varchar
      size: 16
    approved: 
      type: boolean
    updated_at: 
      type: TIMESTAMP
    created_at: 
      type: TIMESTAMP
  menu_image: 
    _attributes: 
      phpName: MenuImage
    id: 
      type: integer
      primaryKey: true
      autoIncrement: true
    restaurant_id: 
    location_id: 
    filename: 
      type: varchar
      size: 255
    approved: 
      type: boolean
    updated_at: 
      type: TIMESTAMP
    created_at: 
      type: TIMESTAMP
  menu_item: 
    _attributes: 
      phpName: MenuItem
    id: 
      type: integer
      primaryKey: true
      autoIncrement: true
    name: 
      type: varchar
      size: 255
    url: 
      type: varchar
      size: 255
    version_id: 
      type: integer
      foreignTable: menuitem_version
      foreignReference: id
    restaurant_id: 
    approved: 
      type: boolean
    average_rating: 
      type: float
      size: 2
      scale: 1
    num_ratings: 
      type: integer
    updated_at: 
      type: TIMESTAMP
    created_at: 
      type: TIMESTAMP
  menuitem_version: 
    id: 
    description: longvarchar
    html_description: longvarchar
    location_id: 
    menuitem_id: {type: integer, foreignTable: menu_item, foreignReference: id} 
    user_id: { type: integer, foreignTable: profile, foreignReference: id }
    price: varchar(16)
    created_at: 
  menuitem_search_index: 
    _attributes: 
      phpName: MenuitemSearchIndex
    menuitem_id: 
      type: integer
      foreignTable: menu_item
      foreignReference: id
    word: 
      type: varchar
      size: 255
      index: true
    weight: 
      type: integer
  restaurant_note: 
    _attributes: { phpName: RestaurantNote }
    id: 
    restaurant_id: 
    user_id: { type: integer, foreignTable: profile, foreignReference: id }
    note: longvarchar
    html_note: longvarchar
    location_id: 
    updated_at:
    created_at: 
  menuitem_note: 
    _attributes: 
      phpName: MenuItemNote
    id: 
      type: integer
      primaryKey: true
      autoIncrement: true
    menu_item_id: 
    user_id: { type: integer, foreignTable: profile, foreignReference: id }
    note: 
      type: longvarchar
    html_note: 
      type: longvarchar
    updated_at: 
    created_at: 
  restaurant_rating: 
    _attributes: 
      phpName: RestaurantRating
    id: 
      type: integer
      primaryKey: true
      autoIncrement: true
    restaurant_id: 
    value: 
      type: integer
    location_id: 
    user_id: 
      type: integer
      foreignTable: profile
      foreignReference: id
    created_at: 
      type: TIMESTAMP
  menuitem_rating: 
    _attributes: 
      phpName: MenuItemRating
    id: 
      type: integer
      primaryKey: true
      autoIncrement: true
    menu_item_id: 
    user_id: 
      type: integer
      foreignTable: profile
      foreignReference: id
    value: 
      type: integer
    created_at: 
      type: TIMESTAMP
  menuitem_tag: 
    menu_item_id: 
    user_id: 
      type: integer
      foreignTable: profile
      foreignReference: id
    tag: 
      type: varchar
      size: 100
    normalized_tag: 
      type: varchar
      size: 100
      index: true
    created_at: 
      type: timestamp
  country: 
    _attributes: 
      phpName: Country
    iso: 
      type: char
      size: 2
      required: true
      primaryKey: true
    name: 
      type: varchar
      size: 80
    printable_name: 
      type: varchar
      size: 80
    iso3: 
      type: char
      size: 3
    numcode: 
      type: smallint
  menu_item_image: 
    _attributes: 
      phpName: MenuItemImage
    id: 
    user_id: 
      type: integer
      foreignTable: profile
      foreignReference: id
    menu_item_id: 
    data: 
      type: blob
    md5sum: 
      type: varchar
      size: 32
  restaurant_tag: 
    restaurant_id: 
      type: integer
      primaryKey: true
      foreignTable: restaurant
      foreignReference: id
    user_id: 
      type: integer
      primaryKey: true
      foreignTable: profile
      foreignReference: id
    created_at: 
      type: timestamp
    tag: 
      type: varchar
      size: 100
    normalized_tag: 
      type: varchar
      size: 100
      primaryKey: true
      index: true
