generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      MenuItem
    theme:            default
    list:
      max_per_page: 10
      display:        [restaurant, =name, description, price, num_ratings, num_reviews]
      filters: [restaurant_id, name]
      actions:
        _create: -
        batch: { name: Batch Update, action: batch }
    edit:
      display: [Restaurant, description, name, url, price]