generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      MenuItem
    theme:            default
    list:
      max_per_page: 10
      display:        [restaurant, name, description, price]
      filters: [restaurant_id]
      actions:
        _create: -
        batch: { name: Batch Update, action: batch }
